### ISSUE TITLE
spector and plotting in toolbar can not be used

### ISSUE THREAD

**Issue by Dushuai12138** [giswqs/GEE-Courses#3]
### Environment Information

-   Package version: 0.19.6
-   Python version: 3.7
-   Operating System: windows10

### Description

I used spector in toolbar of the map, it cannot show any information, and the same as plotting

### What I Did
![1676449372952](https://user-images.githubusercontent.com/116633147/218972363-3ed42dd9-542a-4283-86a0-b21889106b6c.png)
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by giswqs** [comment]
Please open an issue at https://github.com/giswqs/geemap/issues and provide the source code that can reproduce the issue.
